### ISSUE TITLE
na.rm = TRUE

### ISSUE THREAD

**Issue by StevenBlackbeard** [andrewuhl/RollingWindow#1]
Hi Andrew, 

I'm relatively new to R/Github so not sure if this is the way to go about things but please bear with me.

RollingWindow is a truly Amazing package by the way, it's exactly what I've been looking for (in particular the expanding window option) so thank you so much from the outset! 

It doesn't appear to able to handle NA's though so is there any plan to add an "na.rm = TRUE" type argument to the functions?

thanks again

**Comment by andy3rdworld** [comment]
@StevenBlackbeard , I'm going to add that functionality soon - it would make life much easier for sure.

**Comment by andrewuhl** [comment]
Just added basic NA-handling support. See argument **na_rm**.

```R
x = c(1:5, NA, NA, 8:10)
RollingSum(x, window = 2, na_rm = TRUE)
RollingSum(x, window = 2, expanding = TRUE, na_rm = TRUE)
```

**Comment by StevenBlackbeard** [comment]
Great, thanks so much!
